"""empty message

Revision ID: 3385257c0268
Revises: None
Create Date: 2016-07-26 10:04:40.979231

"""

# revision identifiers, used by Alembic.
revision = '3385257c0268'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    ### end Alembic commands ###
